### ISSUE TITLE
Elastic Beanstalk EnvironmentHealth Alarm

### ISSUE THREAD

**Issue by clarkritchie** [swoodford/aws#3]
Your tools look *awesome*!  👏 

Is there a way to automate the creation of an `EnvironmentHealth` alarm for a given Elastic Beanstalk application?  I need to create the exact same alarm for a host of applications, each of which has multiple environments.

e.g.
I have foo-app with foo-app-production and foo-app-staging
I have bar-app with bar-app-production and bar-app-staging

All 4 of those need to message a SNS topic on both Alarm and OK.

**Comment by swoodford** [comment]
Hey @clarkritchie thanks, I'm sure there is a way to do it, I'll take a look when I get some free time!

**Comment by clarkritchie** [comment]
Thanks!  I ended up writing a small Node app to do what I needed, but I do dig your overall framework.  Really nice.
